version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped

    ports:
      - 5001:80

    volumes:
      - ${DOCKER_DATA_PATH}/filebrowser/filebrowser.db:/database.db
      - ${FILEBROWSER_ROOT}:/srv
