version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped

    network_mode: host

    volumes:
      - ${DOCKER_DATA_PATH}/homeassistant/mqtt/config:/mosquitto/config
      - ${DOCKER_DATA_PATH}/homeassistant/mqtt/data:/mosquitto/data
      - ${DOCKER_DATA_PATH}/homeassistant/mqtt/log:/mosquitto/log

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    depends_on:
      - mqtt

    network_mode: host

    volumes:
      - ${DOCKER_DATA_PATH}/homeassistant/config:/config
      - ${DOCKER_DATA_PATH}/homeassistant/ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id:/dev/serial/by-id
