version: "2"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped

    network_mode: host

    volumes:
      - ${DOCKER_DATA_PATH}/mosquitto/config:/mosquitto/config
      - ${DOCKER_DATA_PATH}/mosquitto/data:/mosquitto/data
      - ${DOCKER_DATA_PATH}/mosquitto/log:/mosquitto/log
