version: "3.7"
services:
  actual-server:
    image: jlongster/actual-server:1.0-alpine
    container_name: actual-server
    restart: unless-stopped

    networks:
      - proxy

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/actual/server:/data

networks:
  proxy:
    external: true
