version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: unless-stopped

    networks:
      - proxy
      - smtp

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/calibre-web:/config
      - ${CALIBRE_ROOT}:/books

    environment:
      TZ: ${TZ:-Europe/Berlin}
      PUID: 1540
      PGID: 1540
      
networks:
  proxy:
    external: true
  smtp:
    external: true