services:
  actual-server:
    image: actualbudget/actual-server:latest-alpine
    container_name: actual-server
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/actual/server:/data

networks:
  proxy:
    external: true
