version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser:v2
    container_name: filebrowser
    restart: unless-stopped

    ports:
      - 5001:80

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/filebrowser/filebrowser.db:/database.db
      - ${FILEBROWSER_ROOT}/Medien:/srv/Medien
      - ${FILEBROWSER_ROOT}/Downloads:/srv/Downloads
      - ${FILEBROWSER_ROOT}/Software:/srv/Software
      - ${FILEBROWSER_ROOT}/Backup:/srv/Backup
      - ${FILEBROWSER_ROOT}/Cloud:/srv/Cloud
