version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped

    networks:
      - mqtt

    ports:
      - 1883:1883
      - 9001:9001

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/homeassistant/mqtt/config:/mosquitto/config
      - ${DOCKER_DATA_PATH:-/var/docker}/homeassistant/mqtt/data:/mosquitto/data
      - ${DOCKER_DATA_PATH:-/var/docker}/homeassistant/mqtt/log:/mosquitto/log

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    depends_on:
      - mqtt

    networks:
      - proxy

    ports:
      - 8123:8123

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/homeassistant/config:/config
      - ${DOCKER_DATA_PATH:-/var/docker}/homeassistant/ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id:/dev/serial/by-id

  homeassistant-backup:
    image: tiredofit/db-backup
    container_name: homeassistant-backup
    restart: always
    depends_on:
      - homeassistant

    network_mode: none

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/backups:/backup
      - ${DOCKER_DATA_PATH:-/var/docker}/homeassistant/config/home-assistant_v2.db:/home-assistant.sqlite3

    environment:
      - DB_TYPE=sqlite3
      - DB_HOST=/home-assistant.sqlite3
      - DB_NAME=ALL
      - DB_DUMP_BEGIN=+1
      - DB_CLEANUP_TIME=2880
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - GZ_RSYNCABLE=TRUE
      - CONTAINER_ENABLE_MONITORING=FALSE

networks:
  mqtt:
    name: mqtt
    external: false
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker-mqtt
  proxy:
    external: true
