services:
  jdownloader:
    image: jaymoulin/jdownloader:latest
    container_name: jdownloader
    restart: unless-stopped
    user: ${UID:-1000}:${GID:-1000}

    ports:
      - 3129:3129

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/jdownloader/cfg:/opt/JDownloader/app/cfg
      - ${JD_DOWNLOAD_PATH:-/var/jdownloader}:/opt/JDownloader/Downloads
      - /etc/localtime:/etc/localtime:ro

    environment:
      MYJD_USER: ${MYJD_USER}
      MYJD_PASSWORD: ${MYJD_PASSWORD}
      MYJD_DEVICE_NAME: ${MYJD_NAME}
      UMASK: 002
