services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: 1510:1500
    group_add:
      - ${RENDER_GROUP}
    networks:
      - proxy
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyfin/config:/config
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyfin/cache:/cache
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyfin/web:/jellyfin/jellyfin-web
      - ${JELLYFIN_MEDIA_PATH:-/srv/media}:/media
      - /mnt/nas:/mnt/nas:shared
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

    environment:
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_URL}

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    user: 1510:1500
    depends_on:
      - jellyfin
    networks:
      - proxy
    volumes:
      - /var/docker/jellyseerr/config:/app/config
    environment:
      LOG_LEVEL: debug
      TZ: Europe/Berlin

  jellyfin-backup:
    image: tiredofit/db-backup
    container_name: jellyfin-backup
    restart: always
    depends_on:
      - jellyfin
    network_mode: none
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/.backups:/backup
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyfin/config/data/jellyfin.db:/jellyfin.sqlite3
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyseerr/config/db/db.sqlite3:/jellyseerr.sqlite3
    environment:
      USER_DBBACKUP: ${UID:-1000}
      GROUP_DBBACKUP: ${GID:-1000}
      CONTAINER_ENABLE_MONITORING: false
      DEFAULT_GZ_RSYNCABLE: true
      DEFAULT_CLEANUP_TIME: 2880
      DB01_TYPE: sqlite3
      DB01_HOST: /jellyfin.sqlite3
      DB01_NAME: ALL
      DB02_TYPE: sqlite3
      DB02_HOST: /jellyseerr.sqlite3
      DB02_NAME: ALL

networks:
  proxy:
    external: true
