version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: 1510:1500
    group_add:
      - "106" # Change this to match your "render" host group id and remove this comment

    networks:
      - proxy

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyfin/config:/config
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyfin/cache:/cache
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyfin/web:/jellyfin/jellyfin-web
      - ${JELLYFIN_MEDIA_PATH:-/srv/media}:/media
      - /mnt/nas:/mnt/nas:shared

    environment:
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_URL}

  jellyfin-backup:
    image: tiredofit/db-backup
    container_name: jellyfin-backup
    restart: always
    depends_on:
      - jellyfin

    network_mode: none

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/backups:/backup
      - ${DOCKER_DATA_PATH:-/var/docker}/jellyfin/config/data/jellyfin.db:/jellyfin.sqlite3

    environment:
      - DB_TYPE=sqlite3
      - DB_HOST=/jellyfin.sqlite3
      - DB_NAME=ALL
      - DB_DUMP_BEGIN=+1
      - DB_CLEANUP_TIME=2880
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - GZ_RSYNCABLE=TRUE
      - CONTAINER_ENABLE_MONITORING=FALSE

networks:
  proxy:
    external: true
