version: "2.1"
services:
  root_db:
    image: mysql:5.7
    container_name: nocodb_mysql
    restart: always

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/nocodb/mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: root_db
      MYSQL_USER: noco
      MYSQL_PASSWORD: ${DB_PASSWORD}

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    restart: always
    depends_on:
      root_db:
        condition: service_healthy

    ports:
      - "8080:8080"

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/nocodb/data:/usr/app/data

    environment:
      NC_DB: "mysql2://root_db:3306?u=noco&p=${DB_PASSWORD}&d=root_db"
