services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    user: ${UID:-1000}:${GID:-1000}
    networks:
      - proxy
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/vaultwarden:/data
    environment:
      ROCKET_PORT: 3011
      WEBSOCKET_ENABLED: true
      SIGNUPS_ALLOWED: false
      DOMAIN: ${DOMAIN}

  vaultwarden-backup:
    image: tiredofit/db-backup
    container_name: vaultwarden-backup
    restart: always
    depends_on:
      - vaultwarden
    network_mode: none
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/.backups:/backup
      - ${DOCKER_DATA_PATH:-/var/docker}/vaultwarden/db.sqlite3:/vaultwarden.sqlite3
    environment:
      USER_DBBACKUP: ${UID:-1000}
      GROUP_DBBACKUP: ${GID:-1000}
      CONTAINER_ENABLE_MONITORING: false
      DEFAULT_GZ_RSYNCABLE: true
      DEFAULT_CLEANUP_TIME: 2880
      DB01_TYPE: sqlite3
      DB01_HOST: /vaultwarden.sqlite3
      DB01_NAME: ALL

networks:
  proxy:
    external: true
