version: "3.3"
services:
  stirling-pdf:
    image: ghcr.io/frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped

    networks:
      - proxy

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/stirling-pdf/configs:/configs

    environment:
      - DOCKER_ENABLE_SECURITY=false

networks:
  proxy:
    external: true
