services:
    community:
        image: openproject/community:13
        container_name: openproject
    
        networks:
            - proxy
            
        environment:
            OPENPROJECT_HOST__NAME: projects.lan.${DOMAIN}
            OPENPROJECT_SECRET_KEY_BASE: ${SECRET}
            
        volumes:
            - /var/docker/openproject/pgdata:/var/openproject/pgdata
            - /var/docker/openproject/assets:/var/openproject/assets

networks:
  proxy:
    external: true