services:
  caddy:
    image: ghcr.io/dulli/caddy:2
    container_name: caddy
    restart: unless-stopped
    networks:
      - proxy
      - tunnel
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/static:/srv/static
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/cnames:/srv/cnames
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/redirects:/srv/redirects
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/sites:/srv/sites
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/data:/data
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/config:/config
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/logs:/var/log
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASSWD: ${BASIC_AUTH_PASSWD}
      DOMAIN: ${DOMAIN}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.eth0.proxy_ndp=1

  wireguard-tunnel-server:
    image: ghcr.io/digitallyrefined/docker-wireguard-tunnel:v3
    container_name: caddy-tunnel
    restart: unless-stopped
    networks:
      - tunnel
    ports:
      - '51443:51443/udp'
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/wireguard:/etc/wireguard
    environment:
      - WIREGUARD_PORT=51443
      - DOMAIN=vpn.vps.${DOMAIN}
      - PEERS=1
      - SERVICES=peer1:caddy:8443:8443
    cap_add:
      - NET_ADMIN

networks:
  proxy:
    name: proxy
    external: false
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_PROXY_IPV4}
        - subnet: ${SUBNET_PROXY_IPV6}
    driver_opts:
      com.docker.network.bridge.name: docker-proxy

  tunnel:
    name: tunnel
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_TUNNEL_IPV4}
    driver_opts:
      com.docker.network.bridge.name: docker-tunnel
