version: "2"
services:
  pyload:
    image: ghcr.io/dulli/pyload-ng:0
    container_name: pyload-ng
    restart: unless-stopped
    user: ${UID:-1000}:${GID:-1000}

    ports:
      - 8666:8000 # Webinterface
      - 9666:9666 # Click 'N' Load

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/pyload:/opt/pyload/config
      - ${DOWNLOAD_PATH:-/var/pyload}:/opt/pyload/downloads

  pyload-backup:
    image: tiredofit/db-backup
    container_name: pyload-backup
    restart: always
    depends_on:
      - pyload

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/backups:/backup
      - ${DOCKER_DATA_PATH:-/var/docker}/pyload/data/pyload.db:/pyload.sqlite3

    environment:
      - DB_TYPE=sqlite3
      - DB_HOST=/pyload.sqlite3
      - DB_NAME=ALL
      - DB_DUMP_BEGIN=+1
      - DB_CLEANUP_TIME=2880
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - GZ_RSYNCABLE=TRUE
      - CONTAINER_ENABLE_MONITORING=FALSE
