services:
  db_recipes:
    image: postgres:16-alpine
    container_name: tandoor-postgres
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - /var/docker/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - stack.env

  web_recipes:
    image: vabene1111/recipes
    container_name: tandoor
    restart: unless-stopped
    depends_on:
      - db_recipes
    networks:
      - proxy
      - backend
    volumes:
      - /var/docker/tandoor/mediafiles:/opt/recipes/mediafiles
      - staticfiles:/opt/recipes/staticfiles
      - nginxconf:/opt/recipes/nginx/conf.d
    env_file:
      - stack.env

  nginx_recipes:
    image: nginx:mainline-alpine
    container_name: tandoor-nginx
    restart: unless-stopped
    depends_on:
      - web_recipes
    networks:
      - proxy
      - backend
    volumes:
      - /var/docker/tandoor/mediafiles:/media:ro
      - nginxconf:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
    env_file:
      - stack.env

volumes:
  nginxconf:
  staticfiles:

networks:
  backend:
    driver: bridge
    internal: true
  proxy:
    external: true
