version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    restart: unless-stopped

    networks:
      - proxy
      - backend

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/mealie:/app/data/

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    restart: unless-stopped

    networks:
      - backend
      - smtp

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/mealie:/app/data/

    environment:
      TZ: Europe/Berlin
      BASE_URL: ${BASE_URL}
      PUID: ${UID:-2000}
      PGID: ${GID:-2000}
      SMTP_HOST: smtprelay
      SMTP_PORT: 2525
      SMTP_AUTH_STRATEGY: NONE
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_NAME: ${SMTP_NAME:-Mealie}
      SMTP_FROM_EMAIL: ${SMTP_MAIL}
      #ALLOW_SIGNUP=true

networks:
  proxy:
    external: true
  smtp:
    external: true
  backend:
    driver: bridge
    internal: true
