services:
  hemmelig:
    image: hemmeligapp/hemmelig:v5.19.4
    hostname: hemmelig
    container_name: hemmelig
    init: true
    volumes:
      - /var/docker/hemmelig/files:/var/tmp/hemmelig/upload/files
      - /var/docker/hemmelig/database/:/home/node/hemmelig/database/
    environment:
      SECRET_LOCAL_HOSTNAME: 0.0.0.0
      SECRET_PORT: 3000
      SECRET_HOST: secrets.${DOMAIN_VANITY}
      SECRET_ROOT_USER: ${USER_NAME}
      SECRET_ROOT_PASSWORD: ${USER_PASSWORD}
      SECRET_ROOT_EMAIL: ${USER_EMAIL}
      SECRET_FILE_SIZE: 4 # mb
      SECRET_FORCED_LANGUAGE: en
      SECRET_JWT_SECRET: ${JWT_SECRET}
      SECRET_MAX_TEXT_SIZE: 256 # kb
    networks:
      - proxy
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: 'wget -O /dev/null localhost:3000 || exit 1'
      timeout: 5s
      retries: 1

networks:
  proxy:
    external: true
