version: "3.7"
services:
  smtprelay:
    image: smtprelay:latest
    container_name: smtprelay
    restart: unless-stopped

    networks:
      - smtp

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/smtprelay/users:/etc/smtprelay_users

    environment:
      SMTPRELAY_USERS: /etc/smtprelay_users # username bcrypt-hash [email[,email[,...]]]
      SMTPRELAY_REMOTES: ${REMOTE_PROTOCOL:-starttls}://${REMOTE_USER}:${REMOTE_PASSWORD}@${REMOTE_ADDRESS}:${REMOTE_PORT:-587}

networks:
  smtp:
    name: smtp
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IPV4:-172.125.0.0/16}

    driver_opts:
      com.docker.network.bridge.name: docker-smtp
