services:
  snapserver:
    image: ghcr.io/dulli/snapserver:0
    container_name: snapserver
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/snapcast/server:/root/.config/snapserver
    # environment:
    #   CONFIG_PATH: "/config/snapserver.conf" # optional
