version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    user: ${UID:-1000}:${GID:-1000}

    networks:
      - proxy
      - backend

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/vaultwarden:/data

    environment:
      ROCKET_PORT: 3011
      WEBSOCKET_ENABLED: true
      SIGNUPS_ALLOWED: false
      DOMAIN: ${DOMAIN}

  vaultwarden-backup:
    image: tiredofit/db-backup
    container_name: vaultwarden-backup
    restart: always
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      - vaultwarden

    networks:
      - backend

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/backups:/backup
      - ${DOCKER_DATA_PATH:-/var/docker}/vaultwarden/db.sqlite3:/vaultwarden.sqlite3

    environment:
      - DB_TYPE=sqlite3
      - DB_HOST=/vaultwarden.sqlite3
      - DB_NAME=ALL
      - DB_DUMP_BEGIN=+1
      - DB_CLEANUP_TIME=2880
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - GZ_RSYNCABLE=TRUE
      - CONTAINER_ENABLE_MONITORING=FALSE

networks:
  backend:
    driver: bridge
    internal: true
  proxy:
    external: true
