services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    restart: unless-stopped

    networks:
      - proxy
    ports:
      - "51820:51820/udp"

    environment:
      LANG: de
      WG_HOST: "${EXTERNAL_URL}"
      PASSWORD: "${PASSWORD}"
      
    volumes:
      - /var/docker/wg-easy/etc/wireguard:/etc/wireguard

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1

networks:
  proxy:
    external: true
    