services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    restart: always
    depends_on:
      umami_db:
        condition: service_healthy
    networks:
      - proxy
      - backend
    environment:
      DISABLE_TELEMETRY: 1
      TRACKER_SCRIPT_NAME: ${TRACKER_NAME:-wa.js}
      DATABASE_URL: postgresql://${DB_USER:-umami}:${DB_PASSWORD}@umami_db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${SECRET}

  umami_db:
    image: postgres:15
    container_name: umami_db
    restart: always
    networks:
      - backend
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/umami/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: ${DB_USER:-umami}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  proxy:
    external: true
  backend:
    driver: bridge
    internal: true
